POST http://localhost:5868/wake


###
POST http://localhost:5868/wake

[
  "FC:3F:DB:0D:F0:24",
  "FC:3F:DB:0D:EF:FC",
  "FC:3F:DB:0D:EC:C7",
  "FC:3F:DB:0D:EA:CD"
]

###
GET http://localhost:5868/shut

